#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# 曙光 login 节点上运行：打开浏览器那几步在本地机器完成，粘贴回 ssh 会话即可。
WIZARD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DL_SCRIPT="$WIZARD_DIR/synapse_download.py"
SYNAPSE_CFG="$HOME/.synapseConfig"

banner "Synapse 数据集下载（曙光 login 节点）"

# ── Stage 1: 网络与依赖 ──────────────────────────────────────────────────
stage "网络与依赖检查"
say "曙光出网走平台代理；synapse.org 连不通则后面全部白搭。"
if [[ -n "${https_proxy:-}${HTTPS_PROXY:-}${http_proxy:-}${HTTP_PROXY:-}" ]]; then
  note "代理环境变量：已设置"
else
  warn "未检测到 http(s)_proxy 环境变量"
  step "若 bootstrap 已把平台代理写进 ~/.bashrc，先 source ~/.bashrc 再重跑本脚本。"
fi
if command -v python3 >/dev/null 2>&1; then
  note "python3: $(command -v python3)"
else
  warn "未找到 python3——请先准备 Python 环境后重跑。"
  exit 1
fi
code=$(curl -sS -o /dev/null -w '%{http_code}' --max-time 15 https://www.synapse.org/ 2>/dev/null || true)
code=${code:-000}
if [[ "$code" =~ ^[23] ]]; then
  note "synapse.org 连通（HTTP $code）"
else
  warn "synapse.org 不可达（HTTP $code）——多半是代理没生效，修好代理后重跑本脚本。"
  exit 1
fi
if python3 -c "import synapseclient, synapseutils" 2>/dev/null; then
  note "synapseclient 已安装（$(python3 -c 'import synapseclient; print(synapseclient.__version__)' 2>/dev/null)）"
else
  say "缺少 synapseclient 包。"
  if confirm "现在用 pip 安装 synapseclient？"; then
    if python3 -m pip install synapseclient; then
      note "安装完成"
    else
      warn "pip 安装失败。可换镜像重试：python3 -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple synapseclient"
      exit 1
    fi
  else
    warn "没有 synapseclient 无法下载；装好后重跑本脚本。"
    exit 1
  fi
fi

# ── Stage 2: 数据访问授权 ────────────────────────────────────────────────
stage "Synapse 账号与数据访问授权"
say "Synapse 数据集多半有访问门槛：没过授权，下载必 403，先在这一步解决。"
open_url "https://www.synapse.org/Synapse:syn64377310"
step "登录（没有账号就先注册）。"
step "页面上若有 'Request Access' / Terms of Use / 数据使用协议：提交申请或勾选同意。"
step "需人工审核的数据集要等审核通过再继续。"
if ! confirm "已登录且已获得该数据集的下载权限？"; then
  warn "授权通过后再重跑本脚本即可——已保存的值不会丢。"
  exit 0
fi

# ── Stage 3: Personal Access Token ──────────────────────────────────────
stage "Personal Access Token"
if grep -q '^authtoken' "$SYNAPSE_CFG" 2>/dev/null; then
  note "检测到 $SYNAPSE_CFG 已有 token。"
  if confirm "重新创建并覆盖（旧文件备份为 .bak）？"; then RESET_TOKEN=1; else RESET_TOKEN=0; fi
else
  RESET_TOKEN=1
fi
if [[ "$RESET_TOKEN" == "1" ]]; then
  open_url "https://www.synapse.org/Profile:settings"
  step "页面滚到 'Personal Access Tokens'，点 'Create New Token'。"
  step "名字随意（如 sugon-download）；scope 至少勾 view + download。"
  step "创建后 token 只显示一次——立刻复制。"
  ask_secret SYNAPSE_AUTH_TOKEN "粘贴 token:"
  if [[ -z "${SYNAPSE_AUTH_TOKEN:-}" ]]; then
    warn "token 为空，未写入。重跑本脚本可再来一次。"
    exit 1
  fi
  if [[ -f "$SYNAPSE_CFG" ]]; then cp "$SYNAPSE_CFG" "$SYNAPSE_CFG.bak"; fi
  umask 077
  cat > "$SYNAPSE_CFG" <<EOF
[authentication]
authtoken = $SYNAPSE_AUTH_TOKEN
EOF
  note "已写入 $SYNAPSE_CFG（600 权限，synapseclient 自动读取）"
fi
say "验证 token 能登录："
if python3 -c 'import synapseclient; s=synapseclient.Synapse(); s.login(); print("  登录成功：", s.getUserProfile().get("userName"))'; then
  :
else
  warn "登录失败——token 错误、过期或 scope 不够。重跑本脚本选「重新创建」可重置。"
  exit 1
fi

# ── Stage 4: 下载参数 ────────────────────────────────────────────────────
stage "下载参数"
ask SYNAPSE_ENTITY_ID "Synapse 实体 ID（回车默认 syn64377310）:"
SYNAPSE_ENTITY_ID=${SYNAPSE_ENTITY_ID:-syn64377310}
DEFAULT_DIR="/root/private_data/synapse_${SYNAPSE_ENTITY_ID}"
ask SYNAPSE_DOWNLOAD_DIR "落地目录（回车默认 $DEFAULT_DIR）:"
SYNAPSE_DOWNLOAD_DIR=${SYNAPSE_DOWNLOAD_DIR:-$DEFAULT_DIR}
write_env SYNAPSE_ENTITY_ID "$SYNAPSE_ENTITY_ID"
write_env SYNAPSE_DOWNLOAD_DIR "$SYNAPSE_DOWNLOAD_DIR"
mkdir -p "$SYNAPSE_DOWNLOAD_DIR"
df -h "$SYNAPSE_DOWNLOAD_DIR" | tail -1 | sed 's/^/  磁盘: /'

# ── Stage 5: 生成下载脚本并启动 ──────────────────────────────────────────
stage "生成下载脚本并启动"
cat > "$DL_SCRIPT" <<PYEOF
#!/usr/bin/env python3
"""Synapse 数据集下载（由 synapse_download_wizard.sh 生成，可按实体重新生成）。

断点续传：ifcollision="keep.local" 跳过已下载文件，重跑本脚本即续传。
认证：syn.login() 自动从 ~/.synapseConfig 读 authtoken。
"""
import synapseclient
import synapseutils

ENTITY = "$SYNAPSE_ENTITY_ID"
DEST = "$SYNAPSE_DOWNLOAD_DIR"

syn = synapseclient.Synapse()
syn.login()
files = synapseutils.syncFromSynapse(syn, ENTITY, path=DEST, ifcollision="keep.local")
print(f"done: {len(files)} file(s) -> {DEST}")
PYEOF
note "已生成 $DL_SCRIPT"

PIDFILE="$SYNAPSE_DOWNLOAD_DIR/download.pid"
LOG="$SYNAPSE_DOWNLOAD_DIR/download.log"
if [[ -f "$PIDFILE" ]] && ps -p "$(cat "$PIDFILE")" >/dev/null 2>&1; then
  warn "已有下载进程在跑（PID $(cat "$PIDFILE")），不重复启动。"
  say "看日志: tail -f $LOG"
elif confirm "现在启动后台下载（nohup，断网重跑即续传）？"; then
  nohup python3 "$DL_SCRIPT" > "$LOG" 2>&1 &
  echo $! > "$PIDFILE"
  say "已启动，PID $(cat "$PIDFILE")（继承当前代理环境，断开 ssh 不受影响）"
  say "看日志:  tail -f $LOG"
  say "看进程:  ps -eo pid,args | grep \"[s]ynapse_download\""
  say "要停:    kill \$(cat \"$PIDFILE\")"
  say "中断后重跑同一脚本即断点续传（已下载文件自动跳过）。"
else
  say "稍后手动启动："
  say "  nohup python3 \"$DL_SCRIPT\" > \"$LOG\" 2>&1 &"
fi

finish
