# Copyright (c) MONAI Consortium
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Candidate: image-conditioned ControlNet sample-plan assembly and generation (issue #61).

The trained counterpart of the zero-training img2img baseline. Runs the four-anchor-
round protocol over a manifest side with the frozen P1-DM + the run's trained
ControlNet checkpoint (``controlnet-candidate``): each real modality anchors one
round, the other three target modalities are generated by conditioning the
frozen DM on the anchor's 4ch src latent (with the target modality label riding
the ``class_labels`` path into both DM and ControlNet) and denoising from pure
noise with CFG OFF (``cfg_guidance_scale == 0``, zero latent unconditional
branch — issue #61 acceptance criterion 1-2). It is *not* an interpolated image
start, it is a ControlNet condition.

Outputs (controlled storage, shard-suffixed when ``--num-shards > 1``):

- ``generated/<CH>/<case>/a<src>/<tgt>_seed<seed>.nii.gz`` — candidate volumes;
- ``reference_grid/<CH>/<case>/<tgt>.nii.gz`` — real target volumes resampled
  onto the generation grid (RAS + trilinear 256x256x128, raw intensity domain),
  shared with the baseline run so reference/baseline/candidate triplets align;
- ``samples<...>.json`` — distribution ``four-anchor-plan``-compatible candidate entries
  (variant=controlnet-candidate); the distribution final-acceptance assembly consumes it
  directly;
- ``pairs<...>.json`` — quantitative-side flat candidate records. The full quantitative pair
  triplets are merged by the manifest ``pairs`` builder from the baseline
  reference records plus these candidate volumes.

Run order: select/freeze the candidate first (the run must be frozen before
generation), then ``--side dev`` as a small smoke that only validates the
inference pipeline (its samples are a dev cot; they are not bound to the
contract). The quantitative/distribution/expert-review deliverables it must be auditable against use the
``--side holdout`` samples manifest.

The plan-layer pieces (inference-config validation, run guard, sample plan
builder) are pure logic — stdlib only, no torch/nibabel; the manifest layer came
from the retired candidate plan entry. The generation driver came from the retired
candidate generate entry (ticket 08, ADR-0015 §2); their ``selftest`` subcommands
retired with them.

Usage::

    ctmr generate cross-modal generate candidate \
        --run runs/p3-candidate-.../run.json \
        --manifest /ctrl/phase/phase_manifest.json \
        --out-root /ctrl/p3/candidate_holdout \
        --raw-root /ctrl/phase/raw \
        --stage0-pairs /ctrl/p3/stage0_holdout/pairs.json \
        -e configs/environment_maisi_diff_model_rflow-mr-brain.json \
        -c configs/config_maisi_diff_model_rflow-mr-brain.json \
        -t configs/config_network_p3.json \
        --infer-config configs/config_p3_controlnet_infer.json \
        [--side holdout] [--shard 0 --num-shards 8] [--limit N] [--challenge GLI]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

import nibabel as nib
import numpy as np
import torch
from monai.utils import set_determinism

from ctmr.application.generation.cross_modal.baseline import (
    GRID,
    BaselineGenerateError,
    RawCaseLayout,
    SideCohortBuilder,
)
from ctmr.application.generation.cross_modal.plan import MODALITIES, seed_of
from ctmr.infrastructure.maiisi_engine.diff_model_infer import prepare_tensors
from ctmr.infrastructure.maiisi_engine.diff_model_setting import load_config, setup_logging
from ctmr.infrastructure.maiisi_engine.img2img_infer import load_anchor_latent
from ctmr.infrastructure.maiisi_engine.utils_infer import load_image_models, run_controlnet_conditioned_image_dm

LATENT = (4, 64, 64, 32)
INFER_SCHEMA = "brats-p3-controlnet-infer/1"
SAMPLES_SCHEMA = "brats-p3-candidate-samples/1"
PAIRS_SCHEMA = "brats-l1-pairs/1"
CANDIDATE_VARIANT = "controlnet-candidate"


class CandidatePlanError(Exception):
    """Raised when the inference config or the assembled plan breaks the cross-modal candidate contract."""


class CandidateGenerateError(BaselineGenerateError):
    """Raised when the candidate generation run breaks the cross-modal candidate contract."""


class CandidateInferenceConfig:
    """The official cross-modal candidate inference configuration (configs/config_p3_controlnet_infer.json).

    The candidate is a trained ControlNet that conditions on a 4ch src latent and
    denoises to the target modality from noise with CFG OFF. It differs from the
    baseline config (``brats-p3-stage0-infer/1``): no ``strength`` (the candidate is
    not an interpolated img2img start) and ``cfg_guidance_scale`` is pinned to 0.
    """

    def __init__(self, payload):
        if payload.get("schema") != INFER_SCHEMA:
            raise CandidatePlanError(f"cross-modal candidate inference config schema must be {INFER_SCHEMA!r}")
        self.scheduler = self._text(payload, "scheduler")
        if self.scheduler != "RFlowScheduler":
            raise CandidatePlanError("cross-modal candidate only runs on the RFlow scheduler (rectified flow)")
        self.num_inference_steps = self._positive_int(payload, "num_inference_steps")
        self.cfg_guidance_scale = self._number(payload, "cfg_guidance_scale")
        if self.cfg_guidance_scale != 0:
            raise CandidatePlanError(
                "cross-modal candidate cfg_guidance_scale must be 0 (default CFG off, zero latent unconditional branch; " "issue #61 acceptance criterion 1)"
            )
        if "strength" in payload:
            raise CandidatePlanError("cross-modal candidate inference config must not carry strength (it conditions from noise, not an img2img start)")
        self.grid = self._grid(payload)
        self.modality_tokens = payload.get("modality_tokens")
        if not isinstance(self.modality_tokens, dict) or set(self.modality_tokens) != set(MODALITIES):
            raise CandidatePlanError(f"modality_tokens must cover exactly {list(MODALITIES)} (P1-DM tokens)")
        if not all(isinstance(token, int) and token > 0 for token in self.modality_tokens.values()):
            raise CandidatePlanError("modality tokens must be positive integers (P1-DM class labels)")
        self.seed_rule = self._text(payload, "seed_rule")

    @classmethod
    def from_path(cls, path):
        return cls(json.loads(Path(path).read_text()))

    @staticmethod
    def _text(payload, key):
        value = payload.get(key)
        if not isinstance(value, str) or not value.strip():
            raise CandidatePlanError(f"cross-modal candidate inference config needs a non-empty {key}")
        return value

    @staticmethod
    def _positive_int(payload, key):
        value = payload.get(key)
        if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
            raise CandidatePlanError(f"cross-modal candidate inference config {key} must be a positive integer")
        return value

    @staticmethod
    def _number(payload, key):
        value = payload.get(key)
        if not isinstance(value, int | float) or isinstance(value, bool):
            raise CandidatePlanError(f"cross-modal candidate inference config {key} must be numeric")
        return float(value)

    @staticmethod
    def _grid(payload):
        value = payload.get("grid")
        if not isinstance(value, list | tuple) or len(value) != 3 or not all(isinstance(x, int) and not isinstance(x, bool) and x > 0 for x in value):
            raise CandidatePlanError("cross-modal candidate inference config grid must be three positive integers (SRI24 256x256x128)")
        return tuple(value)


class CandidateRunGuard:
    """Checks the frozen cross-modal candidate run record and pins the ControlNet checkpoint + inference config.

    The generation-time recheck of the phase-run contract markers (issue #61
    acceptance criterion 1-3): the run must be the trained ``controlnet-candidate``
    variant, its selection must pin the trained ControlNet checkpoint (never the
    upstream P1-DM — that would be the zero-training baseline in disguise), and the
    inference config used on the command line must byte-match the
    ``role=inference`` config the run pinned at init.
    """

    def __init__(self, run_record, infer_config_path):
        self._record = run_record
        self._infer_config_path = Path(infer_config_path)

    def check(self):
        record = self._record
        if record.get("phase") != "P3" or record.get("variant") != CANDIDATE_VARIANT:
            raise CandidatePlanError(
                f"run {record.get('run_id')} is not a cross-modal {CANDIDATE_VARIANT} run; "
                "candidate generation must hang off its own trained ControlNet run record"
            )
        if record.get("status") != "frozen":
            raise CandidatePlanError(f"run {record['run_id']} is {record.get('status')}; generate samples only after the freeze")
        selection = record.get("selection") or {}
        checkpoint = selection.get("checkpoint") or {}
        if not checkpoint.get("path") or not checkpoint.get("sha256"):
            raise CandidatePlanError(f"run {record['run_id']} selection carries no candidate checkpoint (the trained ControlNet)")
        path = Path(checkpoint["path"])
        if not path.is_file():
            raise CandidatePlanError(f"candidate ControlNet checkpoint missing: {path}")
        if self.file_sha256(path) != checkpoint["sha256"]:
            raise CandidatePlanError(f"candidate ControlNet checkpoint changed on disk: {path}")
        # anti-confusion (issue #61 acceptance criterion 3): a trained candidate pins its own
        # ControlNet checkpoint, never the upstream P1-DM (that would be the zero-training
        # baseline in disguise, and load_image_models would KeyError on the DM ckpt's missing state_dict)
        upstream = record.get("upstream") or {}
        upstream_sha = upstream.get("checkpoint", {}).get("sha256")
        if upstream_sha and checkpoint["sha256"] == upstream_sha:
            raise CandidatePlanError(
                f"run {record['run_id']} selection pins the upstream P1-DM checkpoint; "
                "a controlnet-candidate must pin its own trained ControlNet checkpoint"
            )
        inference_entries = [entry for entry in record.get("configs", []) if entry.get("role") == "inference"]
        if len(inference_entries) != 1:
            raise CandidatePlanError(
                "the cross-modal candidate run must pin exactly one --config inference=<cross-modal candidate inference config> "
                "(the recorded inference provenance, issue #61 acceptance criterion 1)"
            )
        if self.file_sha256(self._infer_config_path) != inference_entries[0]["sha256"]:
            raise CandidatePlanError(
                f"--infer-config sha256 does not match the config pinned by run {record['run_id']}; "
                "regenerate with the recorded official cross-modal candidate inference config"
            )
        return path

    @staticmethod
    def file_sha256(path):
        digest = hashlib.sha256()
        with open(path, "rb") as handle:
            for chunk in iter(lambda: handle.read(1 << 20), b""):
                digest.update(chunk)
        return digest.hexdigest()


class CandidateSamplePlanBuilder:
    """Builds the distribution-compatible four-anchor entries and the quantitative candidate triplets.

    One real anchor per modality per case; each anchor round conditions the other
    three modalities (12 ordered src->tgt pairs per case). The candidate pairs are
    the merge of the baseline reference volumes with this candidate volume,
    emitted as ``brats-l1-pairs/1`` for the quantitative paired assessor. Every carried
    path marker keeps the ``controlnet-candidate`` variant explicit.
    """

    def __init__(self, run_id, dm_checkpoint_sha256, candidate_checkpoint_sha256, side, config):
        self._run_id = run_id
        self._dm_sha = dm_checkpoint_sha256
        self._candidate_sha = candidate_checkpoint_sha256
        self._side = side
        self._config = config

    def generated_path(self, generated_root, challenge, case, src, tgt):
        seed = seed_of(case, src, tgt)
        return Path(generated_root) / challenge / case / f"a{src}" / f"{tgt}_seed{seed}.nii.gz"

    def entries(self, cohort, real_of, generated_root):
        """``real_of(challenge, case, modality) -> path`` maps each case's real volumes."""
        entries = []
        for item in cohort:
            challenge, case = item["sub"], item["case"]
            anchors = {}
            for anchor in MODALITIES:
                generated = {}
                for tgt in MODALITIES:
                    if tgt == anchor:
                        continue
                    path = self.generated_path(generated_root, challenge, case, anchor, tgt)
                    generated[tgt] = {"path": str(path), "seed": seed_of(case, anchor, tgt)}
                anchors[anchor] = {"real": str(real_of(challenge, case, anchor)), "generated": generated}
            entries.append(
                {
                    "case_id": case,
                    "challenge": challenge,
                    "phase": "P3",
                    "variant": CANDIDATE_VARIANT,
                    "run_id": self._run_id,
                    "side": self._side,
                    "candidate_checkpoint_sha256": self._candidate_sha,
                    "dm_checkpoint_sha256": self._dm_sha,
                    "anchors": anchors,
                }
            )
        return entries

    def pairs(self, stage0_records, generated_root):
        """Merge baseline reference with this candidate volume into ``brats-l1-pairs/1``.

        ``stage0_records`` is the baseline ``brats-p3-stage0-pairs/1`` ``records`` list:
        each carries ``challenge``/``case``/``src_modality``/``target_modality`` plus the
        the ``baseline`` volume and ``reference`` (real target on the generation grid).
        """
        if not isinstance(stage0_records, list):
            raise CandidatePlanError("baseline pairs records must be a list")
        records = []
        for record in stage0_records:
            missing = {"challenge", "case", "src_modality", "target_modality", "baseline", "reference"} - set(record)
            if missing:
                raise CandidatePlanError(f"baseline pair record missing {sorted(missing)}: {record.get('case')}")
            challenge, case = record["challenge"], record["case"]
            src, tgt = record["src_modality"], record["target_modality"]
            candidate = self.generated_path(generated_root, challenge, case, src, tgt)
            records.append(
                {
                    "challenge": challenge,
                    "case": case,
                    "src_modality": src,
                    "target_modality": tgt,
                    "seed": seed_of(case, src, tgt),
                    "reference": record["reference"],
                    "baseline": record["baseline"],
                    "candidate": str(candidate),
                }
            )
        return {
            "schema": PAIRS_SCHEMA,
            "run_id": self._run_id,
            "variant": CANDIDATE_VARIANT,
            "side": self._side,
            "candidate_checkpoint_sha256": self._candidate_sha,
            "records": records,
        }

    def ordered_pairs(self, case):
        """The 12 ordered src!=tgt modality pairs this plan must cover per case."""
        return [(src, tgt) for src in MODALITIES for tgt in MODALITIES if src != tgt]


def load_candidate_models(merged, checkpoint, controlnet_ckpt, device, logger):
    """Load AE + frozen P1-DM + trained ControlNet via the image-side loader.

    Sets ``trained_diffusion_path`` (the frozen P1-DM) and ``trained_controlnet_path``
    (the run's candidate checkpoint) on the merged config; ``load_image_models`` also
    re-initializes the ControlNet from the DM encoder/mid and then overlays the
    trained weights (``strict=False``) — the same "copy_model_state from dm" source
    the training run used, so the candidate inherits no mask-family ControlNet.
    """
    merged.trained_diffusion_path = str(checkpoint)
    merged.trained_controlnet_path = str(controlnet_ckpt)
    autoencoder, unet, controlnet, scale_factor, noise_scheduler = load_image_models(merged, device)
    top_ri, bottom_ri, _spacing, _modality = prepare_tensors(merged, device)
    for model in (autoencoder, unet, controlnet):
        model.to(device).eval()
    logger.info(f"candidate models loaded: DM={merged.trained_diffusion_path} ControlNet={merged.trained_controlnet_path}")
    return autoencoder, unet, controlnet, scale_factor, noise_scheduler, top_ri, bottom_ri


class CandidateSampleWriter:
    """Generates the 12 ordered pairs per case and writes the distribution/quantitative candidate manifests."""

    def __init__(self, merged, run_record, side, config, device, out_root, logger):
        self._merged = merged
        self._run_record = run_record
        self._side = side
        self._config = config
        self._device = device
        self._out_root = Path(out_root)
        self._logger = logger

    @torch.inference_mode()
    def write(self, cohort, layout, stage0_records):
        autoencoder, unet, controlnet, scale_factor, noise_scheduler, top_ri, bottom_ri = load_candidate_models(
            self._merged,
            self._run_record["upstream"]["checkpoint"]["path"],
            self._run_record["selection"]["checkpoint"]["path"],
            self._device,
            self._logger,
        )
        builder = CandidateSamplePlanBuilder(
            self._run_record["run_id"],
            self._run_record["upstream"]["checkpoint"]["sha256"],
            self._run_record["selection"]["checkpoint"]["sha256"],
            self._side,
            self._config,
        )
        generated_root = self._out_root / "generated"
        failures = []
        try:
            for item in cohort:
                challenge, case = item["sub"], item["case"]
                spacing = layout.spacing_of(case)
                spacing_tensor = torch.tensor([[s * 1e2 for s in spacing]], device=self._device).half()
                for anchor in MODALITIES:
                    anchor_path = layout.real_of(challenge, case, anchor)
                    # encode once per anchor; its 4ch latent is the ControlNet condition
                    src_latent = load_anchor_latent(str(anchor_path), autoencoder, self._device, GRID, self._logger)
                    cond = (src_latent * scale_factor).half().to(self._device)
                    for tgt in MODALITIES:
                        if tgt == anchor:
                            continue
                        out = builder.generated_path(generated_root, challenge, case, anchor, tgt)
                        if out.is_file():
                            continue
                        seed = seed_of(case, anchor, tgt)
                        try:
                            set_determinism(seed)
                            modality_tensor = torch.tensor([self._config.modality_tokens[tgt]], device=self._device)
                            synthetic = run_controlnet_conditioned_image_dm(
                                autoencoder,
                                unet,
                                controlnet,
                                noise_scheduler,
                                scale_factor,
                                self._device,
                                controlnet_cond_tensor=cond,
                                spacing_tensor=spacing_tensor,
                                latent_shape=LATENT,
                                output_size=GRID,
                                noise_factor=1.0,
                                top_region_index_tensor=top_ri,
                                bottom_region_index_tensor=bottom_ri,
                                modality_tensor=modality_tensor,
                                num_inference_steps=self._config.num_inference_steps,
                                autoencoder_sliding_window_infer_size=(96, 96, 96),
                                autoencoder_sliding_window_infer_overlap=0.25,
                                cfg_guidance_scale=0.0,
                                controlnet_uncond_tensor=None,
                            )
                            data = synthetic.squeeze().cpu().numpy()
                            data = np.clip(data, 0, None).astype(np.int16)
                            out.parent.mkdir(parents=True, exist_ok=True)
                            nib.save(nib.Nifti1Image(data, affine=np.diag([*spacing, 1.0])), out)
                            self._logger.info(f"[gen] {challenge}/{case}/{anchor}->{tgt} seed={seed} cfg=0")
                        except Exception as error:  # one failed job must not kill the shard
                            failures.append(f"{challenge}/{case}/{anchor}->{tgt}: {error}")
                            self._logger.info(f"[fail] {challenge}/{case}/{anchor}->{tgt}: {error}")
        finally:
            del autoencoder, unet, controlnet
            torch.cuda.empty_cache()
        if failures:
            raise CandidateGenerateError(f"{len(failures)} candidate jobs failed; manifests not written (first: {failures[0]})")

        # pairs triples reference volumes this shard actually generated: scope the
        # baseline records to the shard's cohort so a sharded/filtered run never
        # emits candidate paths it did not create (or 8x-duplicates every shard).
        cohort_keys = {(item["sub"], item["case"]) for item in cohort}
        shard_records = [r for r in stage0_records if (r["challenge"], r["case"]) in cohort_keys]
        entries = builder.entries(cohort, layout.real_of, generated_root)
        pairs = builder.pairs(shard_records, generated_root)
        return entries, pairs


def parse_args(argv=None):
    """The candidate generation entry argparse surface (verbatim from the retired candidate generate entry).

    Exposed for the argv↔namespace equivalence gate (ADR-0015 Testing).
    """
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--run", required=True, help="frozen cross-modal controlnet-candidate run record (run.json)")
    parser.add_argument("--manifest", required=True, help="pinned phase phase_manifest.json")
    parser.add_argument("--out-root", required=True, help="controlled output root")
    parser.add_argument("--raw-root", required=True, help="phase raw root (real BraTS volumes)")
    parser.add_argument("--stage0-pairs", required=True, help="the baseline pairs.json (baseline + reference records) to merge")
    parser.add_argument("-e", "--env_config_path", required=True)
    parser.add_argument("-c", "--model_config_path", required=True)
    parser.add_argument("-t", "--model_def_path", required=True)
    parser.add_argument("--infer-config", required=True, help="the official cross-modal candidate inference config pinned by the run")
    parser.add_argument(
        "--side", default="holdout", choices=("dev", "holdout"), help="dev smoke validates the pipeline only; the contract freeze uses holdout"
    )
    parser.add_argument("--shard", type=int, default=0)
    parser.add_argument("--num-shards", type=int, default=1)
    parser.add_argument("--limit", type=int, default=None, help="max cases per challenge (dev smoke)")
    parser.add_argument("--challenge", default=None)
    parser.add_argument("--only-cases", nargs="*", default=None)
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)

    run_record = json.loads(Path(args.run).read_text())
    try:
        controlnet_ckpt = CandidateRunGuard(run_record, args.infer_config).check()
        config = CandidateInferenceConfig.from_path(args.infer_config)
        manifest = json.loads(Path(args.manifest).read_text())
        stage0_pairs = json.loads(Path(args.stage0_pairs).read_text())
    except (CandidateGenerateError, CandidatePlanError) as error:
        print(error, file=sys.stderr)
        return 1

    if tuple(config.grid) != GRID:
        print(f"cross-modal candidate infer config grid {list(config.grid)} != fixed SRI24 grid {GRID}", file=sys.stderr)
        return 1

    merged = load_config(args.env_config_path, args.model_config_path, args.model_def_path)
    merged.model_dir = str(Path(controlnet_ckpt).parent)

    stage0_records = stage0_pairs.get("records")
    if not isinstance(stage0_records, list):
        print("baseline pairs.json missing records; cannot merge candidate triplets", file=sys.stderr)
        return 1

    cohort = SideCohortBuilder(manifest, args.side, args.shard, args.num_shards, args.limit, args.challenge, args.only_cases).build()
    if not cohort:
        print("empty cohort after sharding/filters; nothing to generate", file=sys.stderr)
        return 1
    layout = RawCaseLayout(args.raw_root, manifest)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    logger = setup_logging("cross-modal-candidate")
    writer = CandidateSampleWriter(merged, run_record, args.side, config, device, args.out_root, logger)
    entries, pairs = writer.write(cohort, layout, stage0_records)

    suffix = f"_shard_{args.shard}" if args.num_shards > 1 else ""
    samples_path = Path(args.out_root) / f"samples{suffix}.json"
    pairs_path = Path(args.out_root) / f"pairs{suffix}.json"
    samples_path.write_text(json.dumps(entries, indent=1) + "\n")
    pairs_path.write_text(json.dumps(pairs, indent=1) + "\n")
    print(f"wrote {len(entries)} case entries -> {samples_path}")
    print(f"wrote {len(pairs['records'])} quantitative triplets (reference+baseline+candidate) -> {pairs_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
